version: '3.1'
services:
  stats-server:
    build: ewm-stats/stats-server
    image: ewm-stats
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    entrypoint:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - stats-server.uri=http://stats-server:9090

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
      - POSTGRES_DB=hits

  ewm-service:
    build: ewm-main
    image: ewm-main
    container_name: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    entrypoint:
      - stats-server.uri=http://stats-server:9090
      - SPRING_DATASOURCE.URL=jdbc:postgresql://ewm-db:5433/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
      - POSTGRES_DB=main
