version: '3.1'
services:
  stats-server:
    build: ewm-stats/stats-server
    image: ewm-stats
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    entrypoint:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
      - POSTGRES_DB=stats

  ewm-service:
    build: ewm-main
    image: ewm-main
    container_name: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    entrypoint:
      - SPRING_DATASOURCE.URL=jdbc:postgresql://ewm-db:5433/ewm-db

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
      - POSTGRES_DB=ewm-db
